@startuml AD_Noti_Detail_Sent
!pragma layout smetana
title Activity Diagram: Xem chi tiết thông báo Nhận

start
 :Người dùng truy cập chức năng "Quản lý thông báo" (UC_Noti_List);
 :Hệ thống hiển thị danh sách tab "Thông báo gửi";
if (Tài khoản có phân quyền xem thông báo) then (Có)
  if (Thông báo tồn tại?) then (Có)
    :Hiển thị màn hình chi tiết thông báo (SCR_Noti_Detail);
    if (Thông báo có file đính kèm?) then (Có)
      :Hiển thị danh sách file đính kèm (có thể tải xuống);
    else (Không)
      :Hiển thị "Không có file đính kèm";
    endif
  else (no)
    :Display "Thông báo đã bị xóa";
  endif
else (no)
  :Display "Không có quyền truy cập";
endif
stop
@enduml