@startuml AD_DM_Donvi_Update
!pragma layout smetana
title Activity Diagram: Chỉnh sửa danh mục đơn vị
start
:Truy cập chức năng "Danh sách danh mục đơn vị";
:Chọn chỉnh sửa danh mục đã có trong danh sách;
:Hiển thị form nhập thông tin chỉnh sửa;
:Nhập thông tin chỉnh sửa danh mục;
:Chọn thao tác;
switch (Thao tác?)
  case (Lưu thông tin)
    :Kiểm tra dữ liệu hợp lệ?;
    if (Dữ liệu hợp lệ?) then (Không)
      :Hiển thị cảnh báo lỗi\n"Nhập thiếu thông tin bắt buộc";
      :Ở lại màn hình\n(**SCR_DM_Donvi_Update**);
    else (Có)
      :Ghi nhận dữ liệu danh mục đơn vị;
      if (Ghi thành công?) then (Có)
        :Thông báo "Chỉnh sửa thông tin danh mục đơn vị thành công";
        :Chuyển hướng về danh sách\n(**SCR_DM_Donvi_List**);
      else (Không)
        :Thông báo lỗi hệ thống;
        :Ở lại màn hình\n(**SCR_DM_Donvi_Update**);
      endif
    endif
  case (Đóng)
    :Xác nhận hủy thao tác?;
    if (Đồng ý?) then (Có)
      :Hủy thao tác;
      :Chuyển hướng về danh sách\n(**SCR_DM_Donvi_List**);
    else (Không)
      :Ở lại màn hình\n(**SCR_DM_Donvi_Update**);
    endif
endswitch
stop
@enduml
