@startuml AD_TSGD_Delete
!pragma layout smetana
title Activity Diagram: Xóa tài sản giao dịch trong màn hình thêm mới/chỉnh sửa giao dịch công chứng

start
:Người dùng đang thực hiện thêm mới/chỉnh sửa giao dịch công chứng\n(**SCR_GDCC_Update** / **SCR_GDCC_Create**);
:Người dùng bấm nút xóa 1 tài sản giao dịch;
:Hệ thống hiển thị popup yêu cầu xác nhận xóa;
if (Người dùng xác nhận?) then (Có)
  :Người dùng bấm nút "Xác nhận";
  :Đóng popup xác nhận và cập nhật lại danh sách tài sản giao dịch trên form giao dịch công chứng\n(**SCR_GDCC_Update** / **SCR_GDCC_Create**);
  :Hiển thị thông báo "Xóa thành công tài sản giao dịch";
else (Không)
  :Người dùng hủy thao tác bằng cách bấm vào nút "Hủy" hoặc biểu tượng đóng popup;
  :Hệ thống đóng popup;
endif
stop
@enduml
