@startuml AD_Noti_Update
!pragma layout smetana
title Activity Diagram: Chỉnh sửa thông báo
start
:Truy cập danh sách thông báo \n(UC_Noti_List);
:Chọn "Chỉnh sửa" trên dòng thông báo cần sửa;

if (Kiểm tra phân quyền chỉnh sửa?) then (yes)
    :Hiển thị form chỉnh sửa với dữ liệu của thông báo hiện tại (SCR_Noti_Update);
    :Người dùng cập nhật thông tin thông báo;
    switch (Thao tác?)
        case (Cập nhật)
            :Kiểm tra tính hợp lệ dữ liệu;
            if (Hợp lệ?) then (yes)
                :Cập nhật dữ liệu thông báo;
                :Hiển thị thông báo "Cập nhật thông báo thành công";
                :Ở lại màn hình (SCR_Noti_Detail) của thông báo vừa chỉnh sửa;
            else (no)
                :Hiển thị lỗi tương ứng;
                :Ở lại màn hình (SCR_Noti_Detail) của thông báo để chỉnh sửa;
            endif
        case (Hủy)
            :Hủy thao tác chỉnh sửa;
            :Quay lại màn hình (SCR_Noti_Detail) của thông báo;
    endswitch
else (no)
    :Hiển thị "Không có quyền truy cập";
endif
stop
@enduml

